Matheus
pgbezerra-org/legendary-guacamole pull request #8
Opened 2023-05-03 04:27 UTC by MatthewLacerda2

Issues #6 #7 targeted

Authentication System coming next

Project running well for now

2023-05-09 22:19 UTC, pgbezerra requested changes
Please restore the gitignore and remove all files that should be not committed.

The PR has 586 changed files, it is much lower.

No binaries can be committed.

https://vegeta2102.medium.com/why-you-should-not-push-binary-files-to-git-and-what-to-do-if-you-do-29f34692cef0

2023-05-09 22:19 UTC, pgbezerra commented on .gitignore
This file should not be deleted.
It will guarantee you do not commit trash, like binaries and other stuff.

2023-05-09 22:20 UTC, pgbezerra commented
Please, update the PR description.
`Matheus` is meaningful for the project.

2023-05-18 02:31 UTC, MatthewLacerda2 commented on .gitignore
Gitignore added, unwanted files removed

2023-05-19 13:53 UTC, pgbezerra approved these changes
The name of the project is webserver. You have changed to razor something.
I'll approve this, but it's not good. We can recreate everything cleaner later.

Also, you run this on Windows, right?
I think this will not boot on Linux. So, doing that, you're on you're own.

2023-05-19 13:53 UTC, pgbezerra commented on LICENSE
This file should not be deleted

2023-05-19 13:53 UTC, pgbezerra commented on README.md
This file should not be deleted.
Please, update the readme, explaining how to run the project.

2023-05-24 20:23 UTC, merged